// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: proto/inventory.proto

package proto

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Seat Status
type SeatStatus int32

const (
	SeatStatus_AVAILABLE SeatStatus = 0
	SeatStatus_RESERVED  SeatStatus = 1
	SeatStatus_BOOKED    SeatStatus = 2
)

// Enum value maps for SeatStatus.
var (
	SeatStatus_name = map[int32]string{
		0: "AVAILABLE",
		1: "RESERVED",
		2: "BOOKED",
	}
	SeatStatus_value = map[string]int32{
		"AVAILABLE": 0,
		"RESERVED":  1,
		"BOOKED":    2,
	}
)

func (x SeatStatus) Enum() *SeatStatus {
	p := new(SeatStatus)
	*p = x
	return p
}

func (x SeatStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SeatStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_inventory_proto_enumTypes[0].Descriptor()
}

func (SeatStatus) Type() protoreflect.EnumType {
	return &file_proto_inventory_proto_enumTypes[0]
}

func (x SeatStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SeatStatus.Descriptor instead.
func (SeatStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_inventory_proto_rawDescGZIP(), []int{0}
}

// Seat message
type Seat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	SeatNumber    string                 `protobuf:"bytes,2,opt,name=seat_number,json=seatNumber,proto3" json:"seat_number,omitempty"`
	Status        SeatStatus             `protobuf:"varint,3,opt,name=status,proto3,enum=inventory.SeatStatus" json:"status,omitempty"`
	UserId        string                 `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Price         float64                `protobuf:"fixed64,5,opt,name=price,proto3" json:"price,omitempty"`
	ReservedAt    int64                  `protobuf:"varint,6,opt,name=reserved_at,json=reservedAt,proto3" json:"reserved_at,omitempty"` // Unix timestamp
	Version       int32                  `protobuf:"varint,7,opt,name=version,proto3" json:"version,omitempty"`                         // Optimistic locking version
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Seat) Reset() {
	*x = Seat{}
	mi := &file_proto_inventory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Seat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Seat) ProtoMessage() {}

func (x *Seat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Seat.ProtoReflect.Descriptor instead.
func (*Seat) Descriptor() ([]byte, []int) {
	return file_proto_inventory_proto_rawDescGZIP(), []int{0}
}

func (x *Seat) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *Seat) GetSeatNumber() string {
	if x != nil {
		return x.SeatNumber
	}
	return ""
}

func (x *Seat) GetStatus() SeatStatus {
	if x != nil {
		return x.Status
	}
	return SeatStatus_AVAILABLE
}

func (x *Seat) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Seat) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Seat) GetReservedAt() int64 {
	if x != nil {
		return x.ReservedAt
	}
	return 0
}

func (x *Seat) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

// GetSeats
type GetSeatsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	EventId        string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	StatusFilter   SeatStatus             `protobuf:"varint,2,opt,name=status_filter,json=statusFilter,proto3,enum=inventory.SeatStatus" json:"status_filter,omitempty"` // Optional
	Limit          int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`                                                             // Pagination limit
	LastSeatNumber string                 `protobuf:"bytes,4,opt,name=last_seat_number,json=lastSeatNumber,proto3" json:"last_seat_number,omitempty"`                    // For pagination
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetSeatsRequest) Reset() {
	*x = GetSeatsRequest{}
	mi := &file_proto_inventory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSeatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSeatsRequest) ProtoMessage() {}

func (x *GetSeatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSeatsRequest.ProtoReflect.Descriptor instead.
func (*GetSeatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_inventory_proto_rawDescGZIP(), []int{1}
}

func (x *GetSeatsRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *GetSeatsRequest) GetStatusFilter() SeatStatus {
	if x != nil {
		return x.StatusFilter
	}
	return SeatStatus_AVAILABLE
}

func (x *GetSeatsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetSeatsRequest) GetLastSeatNumber() string {
	if x != nil {
		return x.LastSeatNumber
	}
	return ""
}

type GetSeatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seats         []*Seat                `protobuf:"bytes,1,rep,name=seats,proto3" json:"seats,omitempty"`
	HasMore       bool                   `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSeatsResponse) Reset() {
	*x = GetSeatsResponse{}
	mi := &file_proto_inventory_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSeatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSeatsResponse) ProtoMessage() {}

func (x *GetSeatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSeatsResponse.ProtoReflect.Descriptor instead.
func (*GetSeatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_inventory_proto_rawDescGZIP(), []int{2}
}

func (x *GetSeatsResponse) GetSeats() []*Seat {
	if x != nil {
		return x.Seats
	}
	return nil
}

func (x *GetSeatsResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

// ReserveSeat
type ReserveSeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	SeatNumber    string                 `protobuf:"bytes,2,opt,name=seat_number,json=seatNumber,proto3" json:"seat_number,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveSeatRequest) Reset() {
	*x = ReserveSeatRequest{}
	mi := &file_proto_inventory_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveSeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveSeatRequest) ProtoMessage() {}

func (x *ReserveSeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveSeatRequest.ProtoReflect.Descriptor instead.
func (*ReserveSeatRequest) Descriptor() ([]byte, []int) {
	return file_proto_inventory_proto_rawDescGZIP(), []int{3}
}

func (x *ReserveSeatRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *ReserveSeatRequest) GetSeatNumber() string {
	if x != nil {
		return x.SeatNumber
	}
	return ""
}

func (x *ReserveSeatRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ReserveSeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Seat          *Seat                  `protobuf:"bytes,3,opt,name=seat,proto3" json:"seat,omitempty"`
	ReservationId string                 `protobuf:"bytes,4,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveSeatResponse) Reset() {
	*x = ReserveSeatResponse{}
	mi := &file_proto_inventory_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveSeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveSeatResponse) ProtoMessage() {}

func (x *ReserveSeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveSeatResponse.ProtoReflect.Descriptor instead.
func (*ReserveSeatResponse) Descriptor() ([]byte, []int) {
	return file_proto_inventory_proto_rawDescGZIP(), []int{4}
}

func (x *ReserveSeatResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReserveSeatResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ReserveSeatResponse) GetSeat() *Seat {
	if x != nil {
		return x.Seat
	}
	return nil
}

func (x *ReserveSeatResponse) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

// ReleaseSeat
type ReleaseSeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	SeatNumber    string                 `protobuf:"bytes,2,opt,name=seat_number,json=seatNumber,proto3" json:"seat_number,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseSeatRequest) Reset() {
	*x = ReleaseSeatRequest{}
	mi := &file_proto_inventory_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseSeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseSeatRequest) ProtoMessage() {}

func (x *ReleaseSeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseSeatRequest.ProtoReflect.Descriptor instead.
func (*ReleaseSeatRequest) Descriptor() ([]byte, []int) {
	return file_proto_inventory_proto_rawDescGZIP(), []int{5}
}

func (x *ReleaseSeatRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *ReleaseSeatRequest) GetSeatNumber() string {
	if x != nil {
		return x.SeatNumber
	}
	return ""
}

func (x *ReleaseSeatRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ReleaseSeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseSeatResponse) Reset() {
	*x = ReleaseSeatResponse{}
	mi := &file_proto_inventory_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseSeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseSeatResponse) ProtoMessage() {}

func (x *ReleaseSeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseSeatResponse.ProtoReflect.Descriptor instead.
func (*ReleaseSeatResponse) Descriptor() ([]byte, []int) {
	return file_proto_inventory_proto_rawDescGZIP(), []int{6}
}

func (x *ReleaseSeatResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReleaseSeatResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// ConfirmBooking
type ConfirmBookingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReservationId string                 `protobuf:"bytes,1,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PaymentId     string                 `protobuf:"bytes,3,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmBookingRequest) Reset() {
	*x = ConfirmBookingRequest{}
	mi := &file_proto_inventory_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmBookingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmBookingRequest) ProtoMessage() {}

func (x *ConfirmBookingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmBookingRequest.ProtoReflect.Descriptor instead.
func (*ConfirmBookingRequest) Descriptor() ([]byte, []int) {
	return file_proto_inventory_proto_rawDescGZIP(), []int{7}
}

func (x *ConfirmBookingRequest) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

func (x *ConfirmBookingRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ConfirmBookingRequest) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

type ConfirmBookingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	BookingId     string                 `protobuf:"bytes,3,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmBookingResponse) Reset() {
	*x = ConfirmBookingResponse{}
	mi := &file_proto_inventory_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmBookingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmBookingResponse) ProtoMessage() {}

func (x *ConfirmBookingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmBookingResponse.ProtoReflect.Descriptor instead.
func (*ConfirmBookingResponse) Descriptor() ([]byte, []int) {
	return file_proto_inventory_proto_rawDescGZIP(), []int{8}
}

func (x *ConfirmBookingResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ConfirmBookingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ConfirmBookingResponse) GetBookingId() string {
	if x != nil {
		return x.BookingId
	}
	return ""
}

// CancelBooking
type CancelBookingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookingId     string                 `protobuf:"bytes,1,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelBookingRequest) Reset() {
	*x = CancelBookingRequest{}
	mi := &file_proto_inventory_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelBookingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelBookingRequest) ProtoMessage() {}

func (x *CancelBookingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelBookingRequest.ProtoReflect.Descriptor instead.
func (*CancelBookingRequest) Descriptor() ([]byte, []int) {
	return file_proto_inventory_proto_rawDescGZIP(), []int{9}
}

func (x *CancelBookingRequest) GetBookingId() string {
	if x != nil {
		return x.BookingId
	}
	return ""
}

func (x *CancelBookingRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type CancelBookingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelBookingResponse) Reset() {
	*x = CancelBookingResponse{}
	mi := &file_proto_inventory_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelBookingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelBookingResponse) ProtoMessage() {}

func (x *CancelBookingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelBookingResponse.ProtoReflect.Descriptor instead.
func (*CancelBookingResponse) Descriptor() ([]byte, []int) {
	return file_proto_inventory_proto_rawDescGZIP(), []int{10}
}

func (x *CancelBookingResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CancelBookingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// InitializeSeats
type InitializeSeatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	TotalSeats    int32                  `protobuf:"varint,2,opt,name=total_seats,json=totalSeats,proto3" json:"total_seats,omitempty"`
	Price         float64                `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitializeSeatsRequest) Reset() {
	*x = InitializeSeatsRequest{}
	mi := &file_proto_inventory_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitializeSeatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitializeSeatsRequest) ProtoMessage() {}

func (x *InitializeSeatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitializeSeatsRequest.ProtoReflect.Descriptor instead.
func (*InitializeSeatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_inventory_proto_rawDescGZIP(), []int{11}
}

func (x *InitializeSeatsRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *InitializeSeatsRequest) GetTotalSeats() int32 {
	if x != nil {
		return x.TotalSeats
	}
	return 0
}

func (x *InitializeSeatsRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type InitializeSeatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	CreatedCount  int32                  `protobuf:"varint,3,opt,name=created_count,json=createdCount,proto3" json:"created_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitializeSeatsResponse) Reset() {
	*x = InitializeSeatsResponse{}
	mi := &file_proto_inventory_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitializeSeatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitializeSeatsResponse) ProtoMessage() {}

func (x *InitializeSeatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitializeSeatsResponse.ProtoReflect.Descriptor instead.
func (*InitializeSeatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_inventory_proto_rawDescGZIP(), []int{12}
}

func (x *InitializeSeatsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *InitializeSeatsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *InitializeSeatsResponse) GetCreatedCount() int32 {
	if x != nil {
		return x.CreatedCount
	}
	return 0
}

var File_proto_inventory_proto protoreflect.FileDescriptor

const file_proto_inventory_proto_rawDesc = "" +
	"\n" +
	"\x15proto/inventory.proto\x12\tinventory\"\xdb\x01\n" +
	"\x04Seat\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1f\n" +
	"\vseat_number\x18\x02 \x01(\tR\n" +
	"seatNumber\x12-\n" +
	"\x06status\x18\x03 \x01(\x0e2\x15.inventory.SeatStatusR\x06status\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userId\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x01R\x05price\x12\x1f\n" +
	"\vreserved_at\x18\x06 \x01(\x03R\n" +
	"reservedAt\x12\x18\n" +
	"\aversion\x18\a \x01(\x05R\aversion\"\xa8\x01\n" +
	"\x0fGetSeatsRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12:\n" +
	"\rstatus_filter\x18\x02 \x01(\x0e2\x15.inventory.SeatStatusR\fstatusFilter\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12(\n" +
	"\x10last_seat_number\x18\x04 \x01(\tR\x0elastSeatNumber\"T\n" +
	"\x10GetSeatsResponse\x12%\n" +
	"\x05seats\x18\x01 \x03(\v2\x0f.inventory.SeatR\x05seats\x12\x19\n" +
	"\bhas_more\x18\x02 \x01(\bR\ahasMore\"i\n" +
	"\x12ReserveSeatRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1f\n" +
	"\vseat_number\x18\x02 \x01(\tR\n" +
	"seatNumber\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\"\x95\x01\n" +
	"\x13ReserveSeatResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12#\n" +
	"\x04seat\x18\x03 \x01(\v2\x0f.inventory.SeatR\x04seat\x12%\n" +
	"\x0ereservation_id\x18\x04 \x01(\tR\rreservationId\"i\n" +
	"\x12ReleaseSeatRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1f\n" +
	"\vseat_number\x18\x02 \x01(\tR\n" +
	"seatNumber\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\"I\n" +
	"\x13ReleaseSeatResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"v\n" +
	"\x15ConfirmBookingRequest\x12%\n" +
	"\x0ereservation_id\x18\x01 \x01(\tR\rreservationId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x03 \x01(\tR\tpaymentId\"k\n" +
	"\x16ConfirmBookingResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x03 \x01(\tR\tbookingId\"N\n" +
	"\x14CancelBookingRequest\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x01 \x01(\tR\tbookingId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"K\n" +
	"\x15CancelBookingResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"j\n" +
	"\x16InitializeSeatsRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1f\n" +
	"\vtotal_seats\x18\x02 \x01(\x05R\n" +
	"totalSeats\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x01R\x05price\"r\n" +
	"\x17InitializeSeatsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12#\n" +
	"\rcreated_count\x18\x03 \x01(\x05R\fcreatedCount*5\n" +
	"\n" +
	"SeatStatus\x12\r\n" +
	"\tAVAILABLE\x10\x00\x12\f\n" +
	"\bRESERVED\x10\x01\x12\n" +
	"\n" +
	"\x06BOOKED\x10\x022\xf8\x03\n" +
	"\x10InventoryService\x12C\n" +
	"\bGetSeats\x12\x1a.inventory.GetSeatsRequest\x1a\x1b.inventory.GetSeatsResponse\x12L\n" +
	"\vReserveSeat\x12\x1d.inventory.ReserveSeatRequest\x1a\x1e.inventory.ReserveSeatResponse\x12L\n" +
	"\vReleaseSeat\x12\x1d.inventory.ReleaseSeatRequest\x1a\x1e.inventory.ReleaseSeatResponse\x12U\n" +
	"\x0eConfirmBooking\x12 .inventory.ConfirmBookingRequest\x1a!.inventory.ConfirmBookingResponse\x12R\n" +
	"\rCancelBooking\x12\x1f.inventory.CancelBookingRequest\x1a .inventory.CancelBookingResponse\x12X\n" +
	"\x0fInitializeSeats\x12!.inventory.InitializeSeatsRequest\x1a\".inventory.InitializeSeatsResponseB\tZ\a./protob\x06proto3"

var (
	file_proto_inventory_proto_rawDescOnce sync.Once
	file_proto_inventory_proto_rawDescData []byte
)

func file_proto_inventory_proto_rawDescGZIP() []byte {
	file_proto_inventory_proto_rawDescOnce.Do(func() {
		file_proto_inventory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_inventory_proto_rawDesc), len(file_proto_inventory_proto_rawDesc)))
	})
	return file_proto_inventory_proto_rawDescData
}

var file_proto_inventory_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_inventory_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_inventory_proto_goTypes = []any{
	(SeatStatus)(0),                 // 0: inventory.SeatStatus
	(*Seat)(nil),                    // 1: inventory.Seat
	(*GetSeatsRequest)(nil),         // 2: inventory.GetSeatsRequest
	(*GetSeatsResponse)(nil),        // 3: inventory.GetSeatsResponse
	(*ReserveSeatRequest)(nil),      // 4: inventory.ReserveSeatRequest
	(*ReserveSeatResponse)(nil),     // 5: inventory.ReserveSeatResponse
	(*ReleaseSeatRequest)(nil),      // 6: inventory.ReleaseSeatRequest
	(*ReleaseSeatResponse)(nil),     // 7: inventory.ReleaseSeatResponse
	(*ConfirmBookingRequest)(nil),   // 8: inventory.ConfirmBookingRequest
	(*ConfirmBookingResponse)(nil),  // 9: inventory.ConfirmBookingResponse
	(*CancelBookingRequest)(nil),    // 10: inventory.CancelBookingRequest
	(*CancelBookingResponse)(nil),   // 11: inventory.CancelBookingResponse
	(*InitializeSeatsRequest)(nil),  // 12: inventory.InitializeSeatsRequest
	(*InitializeSeatsResponse)(nil), // 13: inventory.InitializeSeatsResponse
}
var file_proto_inventory_proto_depIdxs = []int32{
	0,  // 0: inventory.Seat.status:type_name -> inventory.SeatStatus
	0,  // 1: inventory.GetSeatsRequest.status_filter:type_name -> inventory.SeatStatus
	1,  // 2: inventory.GetSeatsResponse.seats:type_name -> inventory.Seat
	1,  // 3: inventory.ReserveSeatResponse.seat:type_name -> inventory.Seat
	2,  // 4: inventory.InventoryService.GetSeats:input_type -> inventory.GetSeatsRequest
	4,  // 5: inventory.InventoryService.ReserveSeat:input_type -> inventory.ReserveSeatRequest
	6,  // 6: inventory.InventoryService.ReleaseSeat:input_type -> inventory.ReleaseSeatRequest
	8,  // 7: inventory.InventoryService.ConfirmBooking:input_type -> inventory.ConfirmBookingRequest
	10, // 8: inventory.InventoryService.CancelBooking:input_type -> inventory.CancelBookingRequest
	12, // 9: inventory.InventoryService.InitializeSeats:input_type -> inventory.InitializeSeatsRequest
	3,  // 10: inventory.InventoryService.GetSeats:output_type -> inventory.GetSeatsResponse
	5,  // 11: inventory.InventoryService.ReserveSeat:output_type -> inventory.ReserveSeatResponse
	7,  // 12: inventory.InventoryService.ReleaseSeat:output_type -> inventory.ReleaseSeatResponse
	9,  // 13: inventory.InventoryService.ConfirmBooking:output_type -> inventory.ConfirmBookingResponse
	11, // 14: inventory.InventoryService.CancelBooking:output_type -> inventory.CancelBookingResponse
	13, // 15: inventory.InventoryService.InitializeSeats:output_type -> inventory.InitializeSeatsResponse
	10, // [10:16] is the sub-list for method output_type
	4,  // [4:10] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_proto_inventory_proto_init() }
func file_proto_inventory_proto_init() {
	if File_proto_inventory_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_inventory_proto_rawDesc), len(file_proto_inventory_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_inventory_proto_goTypes,
		DependencyIndexes: file_proto_inventory_proto_depIdxs,
		EnumInfos:         file_proto_inventory_proto_enumTypes,
		MessageInfos:      file_proto_inventory_proto_msgTypes,
	}.Build()
	File_proto_inventory_proto = out.File
	file_proto_inventory_proto_goTypes = nil
	file_proto_inventory_proto_depIdxs = nil
}
